# Generated by Django 4.1.1 on 2022-09-28 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RefNo', models.CharField(default='', max_length=100)),
                ('Deadline', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('From', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('To', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('City', models.CharField(default='', max_length=100)),
                ('Country', models.CharField(default='', max_length=100)),
                ('GeneralDisciplines', models.CharField(default='', max_length=500)),
                ('FieldsOfStudy', models.CharField(default='', max_length=500)),
                ('RequiredKnowledgeAndExperiences', models.CharField(default='', max_length=500)),
                ('OtherRequirements', models.CharField(default='', max_length=500)),
                ('CompletedYearsOfStudy', models.IntegerField(default=0)),
                ('LanguageRequirements', models.CharField(default='', max_length=500)),
                ('WorkWeeksMin', models.IntegerField(default=0)),
                ('WorkWeeksMax', models.IntegerField(default=0)),
                ('AlternativeFrom', models.CharField(default='', max_length=100)),
                ('AlternativeTo', models.CharField(default='', max_length=100)),
                ('CompanyClosedFrom', models.CharField(default='', max_length=100)),
                ('CompanyClosedTo', models.CharField(default='', max_length=100)),
                ('WorkOfferedDescription', models.CharField(default='', max_length=2000)),
                ('GrossPay', models.CharField(default='', max_length=100)),
                ('WorkingHours', models.CharField(default='', max_length=100)),
                ('Employer', models.CharField(default='', max_length=200)),
                ('Workplace', models.CharField(default='', max_length=100)),
                ('Website', models.URLField(default='', max_length=300)),
                ('LodgingBy', models.CharField(default='', max_length=100)),
                ('LivingCost', models.CharField(default='', max_length=100)),
                ('EstCostOfLodging', models.CharField(default='', max_length=100)),
                ('AdditionalInfo', models.CharField(default='', max_length=500)),
                ('OfferType', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
