# Generated by Django 4.1.1 on 2022-09-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaesteTable', '0002_alter_offer_deadline_alter_offer_from_alter_offer_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='CompletedYearsOfStudy',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Website',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='offer',
            name='WorkWeeksMax',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='WorkWeeksMin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
