# Generated by Django 4.1.1 on 2022-09-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RefNo', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Deadline', models.CharField(max_length=200)),
            ],
        ),
    ]
